### PR TITLE
Added Places Carousel and Made BGimage static

### LINKED ISSUE #25: Add places of attractions below the venue
Add places of attractions in a carousel - St Mary's Island , Kudremukh , malpe, gokarna, Western Ghats, Moodbidri, Murdeshwar. @pvgupta24  Please help them with the carousel

### PR DESCRIPTION
**Pull request by nimbus98**
Issues resolved:
Closes #25 
Made a Carousel with the required places and along with their headers with each image

#6 
Made the image static before, but due to revert changes it became non static, so I fixed it again.

Collab Page Coming Soon

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
Fix the size of the carousel. It is changing for different images.

**Comment by nimbus98** [comment]
Fixed the size of carousel

**Comment by sbshah97** [comment]
Can you please put up a screenshot of the changes that you made so that it's easier to review.

**Comment by anumehaagrawal** [comment]
@nimbus98  Good work !

**Comment by nimbus98** [comment]
@salman-bhai  Alright yeah I understand. I'll try doing that next time.
@anumehaagrawal  Thanks!

**Pull request merged**
