### PR TITLE
Registration subsections added

### PR DESCRIPTION
**Pull request by nimbus98**
#40 
Resolved.

These changes were made.

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
@nimbus98  Can you add both these subsections in one row ? Non nitk delegates section to the right of nitk delegates ?

**Comment by nimbus98** [comment]
yeah sure, on it

**Comment by nimbus98** [comment]
Done.

**Comment by anumehaagrawal** [comment]
Could you make the buttons aligned ? So they appear to be in the same line and its fine if there is space above the button in NITK delegates

**Comment by nimbus98** [comment]
Yes, Done.

**Pull request merged**
