### PR TITLE
Adds schedule

### LINKED ISSUE #58: Add schedule
Please add schedule from here: https://docs.google.com/document/d/1Zb41qCJLSBGd1AxaUyMdh-970uhx1I2TR6hwYE1bh0Q/edit?usp=sharing

### PR DESCRIPTION
**Pull request by pvgupta24**
Resolves #58 
[Schedule doc](https://docs.google.com/document/d/1Zb41qCJLSBGd1AxaUyMdh-970uhx1I2TR6hwYE1bh0Q/edit)

screenshot from 2018-12-08 04-28-52

### CODE REVIEW

**Review by sbshah97 — APPROVED** [review]
Code looks good to me!

**Comment by SamarthBonthala** [comment]
@SagarB-97 are we sure of the schedule. Some rework is needed in the schedule. Can't we stall it for some time before we release it. A few workshops slots have been approached by mutliple companies and lets resolve that first before releasing schedule like this. My opinion. @salman-bhai any comment on this?

**Comment by sagar-bharadwaj-ks** [comment]
@SamarthBonthala Let us just rename the section into tentative schedule and release. This will help Open pass registrants plan their travel. This is important as Open pass registrants will have to decide which days to attend. What say?

**Comment by SamarthBonthala** [comment]
Yeah make it tentative schedule.

**Review by sagar-bharadwaj-ks — APPROVED** [review]
Looks good

**Pull request merged**
