### PR TITLE
contact us 

### PR DESCRIPTION
**Pull request by Saharsh007**
contact us section added
code of conduct removed
screenshot here

### CODE REVIEW

**Comment by anumehaagrawal** [comment]
Have one big box with color same as background . Maintain same gradient as background and two contacts in a row . Also font style  should be  same as the rest of the content

**Comment by Saharsh007** [comment]
Review please

**Comment by anumehaagrawal** [comment]
Looks better, left align contact us title and make it the same thickness as the rest of the headings like places of attraction

**Comment by Saharsh007** [comment]
So i changed the format accordingly
Please review
Screenshot Below

**Comment by anumehaagrawal** [comment]
Good work !

**Pull request merged**
